import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html>
      <Head>
        <title>Fitness Freak</title>
        <meta name="description" content="Generated by Team Neuronious" />
        <link rel="icon" href="/frame.svg" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
